- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade all packages
  apt:
    upgrade: dist
  register: upgrade_result
  become: true

- name: Reboot if kernel or initramfs was updated
  reboot:
    msg: "Rebooting due to kernel/initramfs update"
    connect_timeout: 5
    reboot_timeout: 600
    test_command: uptime
  when: upgrade_result.stdout is search("linux-image|initramfs")
  become: true

- name: Wait for server to be reachable again
  wait_for_connection:
    timeout: 300
  become: false

- name: Install base system packages and build dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - gnupg
      - lsb-release
      - git
      - python3
      - python3-pip
      - python3-apt
      - libffi-dev
      - libssl-dev
      - iptables
      - software-properties-common
      - build-essential
    state: present
    update_cache: yes
  become: true

- name: Ensure required Python packages are installed for Ansible + Docker
  pip:
    name:
      - requests
      - docker
    executable: pip3
  become: true

- name: Verify core CLI tools are available
  shell: command -v {{ item }}
  loop:
    - curl
    - git
    - python3
    - pip3
  register: bin_check
  changed_when: false
  failed_when: bin_check.rc != 0
