all:
  children:
    cloud:
      hosts:
        homelab-gateway:
          ansible_host: IP_ADDRESS_OF_HOMELAB_GATEWAY
          ansible_user: YOUR_ANSIBLE_USERNAME
          ansible_become: true
          ansible_become_method: sudo

        racknerd:
          ansible_host: IP_ADDRESS_OF_RACKNERD_VPS
          ansible_user: YOUR_ANSIBLE_USERNAME
          ansible_become: true
          ansible_become_method: sudo
          ansible_ssh_private_key_file: /home/YOUR_LOCAL_USER/.ssh/ID_OF_RACKNERD_KEY
